version: '3'
services:
  web:
    image: docker-spring-boot
    ports:
    - 8085:8085
    links:
    - postgres
    volumes:
    - d:/docker/log:/log
  postgres:
    container_name: spring-postgresql
    image: postgres
    environment:
    - POSTGRES_PASSWORD=postgres